version: '3'
services:
  mariadb:
    build: /home/tyrant/Desktop/inception/srcs/requirements/mariadb
    container_name: mariadb
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - db_data:/home/kouferka/data/database
    networks:
      - inception_network
  
  nginx:
    build: /home/tyrant/Desktop/inception/srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp_data:/home/kouferka/data/wordpress
    networks:
      - inception_network
    
  wordpress:
    build: /home/tyrant/Desktop/inception/srcs/requirements/wordpress
    container_name: wordpress
    ports:
      - 9000
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp_data:/home/kouferka/data/wordpress
    networks:
      - inception_network

  redis:
      build: /home/tyrant/Desktop/inception/srcs/requirements/bonus/redis
      container_name: redis
      ports:
        - 6379
      networks:
        - inception_network

volumes:
  db_data:
  wp_data:

networks:
  inception_network:
  