version: '3'
services:
  mariadb:
    build: /home/tyrant/Desktop/inception/srcs/requirements/mariadb
    container_name: mariadb
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
  
  nginx:
    build: /home/tyrant/Desktop/inception/srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    
  wordpress:
    build: /home/tyrant/Desktop/inception/srcs/requirements/wordpress
    container_name: wordpress
    ports:
      - 9000
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network

volumes:
  db_data:
  wp_data:

networks:
  inception_network:
    driver: bridge