version: '3'
services:
  mariadb:
    container_name: mariadb
    build: /home/tyrant/Desktop/inception/srcs/requirements/mariadb
    ports:
      - 3306
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
  
  nginx:
    container_name: nginx
    build: /home/tyrant/Desktop/inception/srcs/requirements/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wp_data:/wordpress
    networks:
      - inception_network
    restart: always

    
  wordpress:
    container_name: wordpress
    build: /home/tyrant/Desktop/inception/srcs/requirements/wordpress
    ports:
      - 9000
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp_data:/wordpress
    networks:
      - inception_network
    restart: always

  redis:
    container_name: redis
    build: /home/tyrant/Desktop/inception/srcs/requirements/bonus/redis
    ports:
      - 6379
    networks:
      - inception_network
    restart: always

  ftp:
    container_name: ftp
    build: /home/tyrant/Desktop/inception/srcs/requirements/bonus/ftp
    ports:
      - 21
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception_network
    volumes:
      - wp_data:/wordpress
    restart: always

  adminer:
    container_name: adminer
    build: /home/tyrant/Desktop/inception/srcs/requirements/bonus/adminer
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception_network
    restart: always

volumes:
    wp_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/kouferka/data/wordpress
    db_data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/kouferka/data/database

networks:
  inception_network:
  